version: '2'
services:
    ksams-postgresql:
        image: postgres:16.3-alpine3.20
        environment:
            - POSTGRES_DB=dev
            - POSTGRES_USER=eric
            - POSTGRES_PASSWORD=3r1c
        ports:
            - "5434:5432"
